colorGroup(a1, brown).
colorGroup(a2, brown).
colorGroup(a3, brown).
colorGroup(b1, cyan).
colorGroup(b2, cyan).
colorGroup(b3, cyan).
colorGroup(c1, magenta).
colorGroup(c2, magenta).
colorGroup(c3, magenta).
colorGroup(d1, orange).
colorGroup(d2, orange).
colorGroup(d3, orange).
colorGroup(e1, red).
colorGroup(e2, red).
colorGroup(e3, red).
colorGroup(f1, yellow).
colorGroup(f2, yellow).
colorGroup(f3, yellow).
colorGroup(g1, green).
colorGroup(g2, green).
colorGroup(g3, green).
colorGroup(h1, blue).
colorGroup(h2, blue).

colorGroupLength(brown, 3).
colorGroupLength(cyan, 3).
colorGroupLength(magenta, 3).
colorGroupLength(orange, 3).
colorGroupLength(red, 3).
colorGroupLength(yellow, 3).
colorGroupLength(green, 3).
colorGroupLength(blue, 2).
